#!/bin/sh
set -xe

# Do not install recommended packages by default
echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/99no-recommends

# Make sure our packages list is updated
apt-get update

# We install an up to date git version because we might be using commands only
# present in modern versions. For this we need python-software-properties /
# software-properties-common packages that provide add-apt-repository (for
# easily installing PPAs).
apt-get -y install apt-transport-https build-essential bzip2 devscripts \
	sudo debhelper less lsb-release vim wget curl adduser fakeroot \
	python3 python-docutils python-pil python-pygments \
	python-software-properties software-properties-common

# Update the whole system
apt-get -y dist-upgrade
