#!/bin/sh
# Copyright sociomantic labs GmbH 2017.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
set -xeu

# Get utility stuff
. ./util.sh

# Do not install recommended packages by default
echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/99no-recommends

# Make sure our packages list is updated
apt update

# We install some basic packages first.
apt -y install apt-transport-https build-essential bzip2 devscripts \
	sudo debhelper less lsb-release vim wget curl adduser fakeroot \
	python3 python-docutils python-pil python-pygments \
	python-software-properties software-properties-common \
	ruby-dev rubygems-integration jq git

# Add extra APT repositories from Sociomantic in Bintray
dist="$(lsb_release -cs)"

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
echo '# Sociomantic Tsunami repos' \
	> /etc/apt/sources.list.d/sociomantic-tsunami.list
echo "deb https://dl.bintray.com/sociomantic-tsunami/tools $dist release" \
	>> /etc/apt/sources.list.d/sociomantic-tsunami.list

# Get the new packages list
apt update

# Update the whole system
apt -y full-upgrade

# fpm installation is release-dependant
gem install $(gem_ver travis "$VERSION_TRAVIS")

# fpm installation is release-dependant
gem install $(gem_ver fpm "$VERSION_FPM")

# Get jfrog tool from Bintray
download_jfrog()
{
	{ set +x; } > /dev/null
	local ver="$1"
	local dst="/usr/local/bin/jfrog"

	# Get sha256 sum of the file
	local json=$(set -x; curl -sLkX GET \
		"https://api.bintray.com/packages/jfrog/jfrog-cli-go/jfrog-cli-linux-amd64/versions/$ver/files")
	# From the received array, select the object with the specific "path"
	# attribute, and from that object get the "sha256" attribute
	local sha256=$(echo "$json" | jq -r ".[] |
			select(.path == \"$ver/jfrog-cli-linux-amd64/jfrog\") |
			.sha256")

	# Get the file
	(set -x; curl -#LkX GET \
		"https://dl.bintray.com/jfrog/jfrog-cli-go/$ver/jfrog-cli-linux-amd64/jfrog" \
		> "$dst")

	# Check file's sha256 sum
	local sha256new="$(sha256sum "$dst" | cut -c1-64)"
	set -x
	test "$sha256new" = "$sha256"

	# Make it executable
	chmod a+x "$dst"
}
download_jfrog "$VERSION_JFROG"

# Remove common temporary files and packages
cleanup
