#!/bin/sh
# Copyright sociomantic labs GmbH 2017.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
set -xeu

# Get utility stuff
. ./util.sh


# Add extra DMD D-APT repo
dist="$(lsb_release -cs)"
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EBCF975E5BA24D5E
wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list \
               -O /etc/apt/sources.list.d/d-apt.list

# Add extra dlang APT repositories from Sociomantic in Bintray
echo "deb https://dl.bintray.com/sociomantic-tsunami/dlang $dist release" \
        >> /etc/apt/sources.list.d/sociomantic-tsunami.list

# Add extra dlang-community APT repository (also in Bintray)
echo '# dlang-community repos' \
        > /etc/apt/sources.list.d/dlang-community.list
echo "deb https://dl.bintray.com/dlang-community/apt $dist release" \
        >> /etc/apt/sources.list.d/dlang-community.list


# Install dlang packages
apt update
apt_pin_install \
	libebtree6="$VERSION_EBTREE" \
		libebtree6-dbg="$VERSION_EBTREE" \
		libebtree6-dev="$VERSION_EBTREE" \
	dmd1="$VERSION_DMD1" \
	libtangort-dmd-dev="$VERSION_TANGORT" \
	dmd-transitional="$VERSION_DMD_TRANSITIONAL" \
	d1to2fix="$VERSION_D1TO2FIX" \
	dmd-bin="$VERSION_DMD" \
		libphobos2-dev="$VERSION_DMD"

# Remove common temporary files and packages
cleanup
