#!/bin/sh
# Copyright sociomantic labs GmbH 2017.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
set -xeu

# Get utility stuff
. ./util.sh

# Install dlang packages
apt update
apt -y_install \
	libebtree6="$VERSION_EBTREE" \
		libebtree6-dbg="$VERSION_EBTREE" \
		libebtree6-dev="$VERSION_EBTREE" \
	dmd1="$VERSION_DMD1" \
	libtangort-dmd-dev="$VERSION_TANGORT" \
	dmd-transitional="$VERSION_DMD_TRANSITIONAL" \
	d1to2fix="$VERSION_D1TO2FIX" \
	dmd-bin="$VERSION_DMD" \
		libphobos2-dev="$VERSION_DMD"

# Remove common temporary files and packages
cleanup
