#!/bin/sh
set -xe

image=$1
shift

path=$(readlink -f "$(dirname $0)/$image")

# Temporary build directory
tmpdir=$(mktemp -d)
cd "$tmpdir"

for s in "$@"
do
	$path/$s
done

cd -

# Clean all temporary apt files
apt-get -y autoremove
apt-mark showauto | apt purge -y
apt-get -y clean
rm -rf /var/lib/apt/lists/*
rm -fr $tmpdir
