#!/bin/sh
set -xe

VERSION_D1TO2FIX=${1:-$VERSION_D1TO2FIX}

releases_api_url="https://api.github.com/repos/sociomantic-tsunami/d1to2fix/releases/latest"
if [ -z "$VERSION_D1TO2FIX" ]
then
    VERSION_D1TO2FIX=$(curl -s "$releases_api_url" |
            sed -n 's/^.*"tag_name": "\(.*\)".*$/\1/p')
fi

# Get & build
git clone --depth 50 --branch "$VERSION_D1TO2FIX" \
        https://github.com/sociomantic-tsunami/d1to2fix.git
cd d1to2fix
git submodule update --init
make all deb

# Install the resulting package
dpkg -i deb/d1to2fix_*.deb
