#!/bin/sh
set -xe

VERSION_DMD=${1:-$VERSION_DMD}

# Install D-APT packages
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EBCF975E5BA24D5E && \
        wget http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list \
            -O /etc/apt/sources.list.d/d-apt.list

# Make sure our packages list is updated
apt-get update

# Install dmd-bin
deb_version=${VERSION_DMD:+=$VERSION_DMD}
apt-get install -y dmd-bin$deb_version libphobos2-dev$deb_version
