#!/bin/sh
set -xe

VERSION_EBTREE=${1:-$VERSION_EBTREE}

releases_api_url="https://api.github.com/repos/sociomantic-tsunami/ebtree/releases/latest"
if [ -z "$VERSION_EBTREE" ]
then
    VERSION_EBTREE=$(curl -s "$releases_api_url" |
            sed -n 's/^.*"tag_name": "\(.*\)".*$/\1/p')
fi

# Get & build
git clone --depth 50 --branch "$VERSION_EBTREE" \
        https://github.com/sociomantic-tsunami/ebtree.git
cd ebtree
git submodule update --init
make -r deb

# Install the resulting package
dpkg -i deb/libebtree6_*.deb deb/libebtree6-dev_*.deb
