#!/bin/sh
set -xe

VERSION_TANGORT=${1:-$VERSION_TANGORT}

releases_api_url="https://api.github.com/repos/sociomantic-tsunami/tangort/releases/latest"
if [ -z "$VERSION_TANGORT" ]
then
    VERSION_TANGORT=$(curl -s "$releases_api_url" |
            sed -n 's/^.*"tag_name": "\(.*\)".*$/\1/p')
fi

# Get & build
git clone --depth 50 --branch "$VERSION_TANGORT" \
        https://github.com/sociomantic-tsunami/tangort.git
cd tangort
git submodule update --init
make -r pkg

# Install the resulting package
dpkg -i build/last/pkg/libtangort-dmd-dev_*.deb
